typography_spectrum: 0.314665314508602
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7076168225612491
  lightness: 0.2650747278239578
  saturation: 0.6464473376981914
  rhythmicContrast: 0.4464193682651967
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.29034394258633256
analytics:
  google: null
  facebook: null
  twitter: null
name: Performers - Entertainers - Circus - Events
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Spark Fire Dance
    url: 'http://sparkfiredance.com'
    type: external
favicon: null
title: Spark Fire Productions
purpose: []
